name: binder_env
channels:
- defaults
dependencies:
- pandas=1.2.4
- python=3.8.6
- pip
- tensorflow=2.4.0
- opencv
- pip:
  - tensorflow==2.4.0
  - keras==2.4.3
  - astropy==4.2.1
  - numpy==1.19.1
  - scipy==1.7.1
  - scikit-learn==0.24.2
  - scikit-image==0.18.2
  - matplotlib==3.4.2
  - opencv-python 
