name: binder_env
channels:
- defaults
dependencies:
- pandas=1.1.5
- python=3.6.8
- pip
- tensorflow=1.15.0
- pip:
  - h5py==2.10.0
  - tensorflow==1.15.0
  - keras==2.2.4
  - numpy==1.19.2
  - scikit-learn==0.24.2
