name: binder_env
channels:
- defaults
dependencies:
- pandas=1.3.4
- python=3.9.7
- pip
- pip:
  - tensorboard==2.7.0
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.0
  - tensorflow==2.6.1
  - tensorflow-estimator==2.6.0
  - tensorflow-gpu==2.6.0
  - tensorflow-probability==0.14.1
  - numpy
  - keras==2.6.0
  - scikit-learn
  - sklearn
  - matplotlib==3.4.3
  - matplotlib-inline==0.1.3
  - seaborn==0.11.2
  - scipy==1.7.1
